import { PrismaClient } from '@prisma/client'
import * as fs from 'fs'
import * as path from 'path'

const prisma = new PrismaClient()

interface CloudinaryFile {
  name: string
  type: string
  path: string
  thumbnail: string
  galleryPath: string
}

async function main() {
  // Clear existing data
  await prisma.sidebarOption.deleteMany()
  await prisma.sidebarSection.deleteMany()
  await prisma.fileItem.deleteMany()

  // Create Print files section
  const printFiles = await prisma.sidebarSection.create({
    data: {
      name: 'Print files',
      order: 1,
      options: {
        create: [
          { name: 'Stickers', icon: 'sticker', path: '/print/stickers', order: 1 },
          { name: 'DTF', icon: 'dtf', path: '/print/dtf', order: 2 },
          { name: 'DIY recomendations', icon: 'palette', path: '/print/diy', order: 3 },
        ],
      },
    },
  })

  // Create Gallery section
  const gallery = await prisma.sidebarSection.create({
    data: {
      name: 'Gallery',
      order: 2,
      options: {
        create: [
          { name: '(2018) First steps', icon: 'gallery', path: '/gallery/2018-first-steps', order: 1 },
          { name: '(2023) Fatrap x Caribu', icon: 'gallery', path: '/gallery/2023-fatrap-caribu', order: 2 },
          { name: '(2024) Fatrap College', icon: 'gallery', path: '/gallery/2024-fatrap-college', order: 3 },
          { name: '(2024) Les Santes Olimpiques', icon: 'gallery', path: '/gallery/2024-les-santes-olimpiques', order: 4 },
          { name: "(2025) Fatrap Don't Stay Relevant", icon: 'gallery', path: '/gallery/2025-dont-stay-relevant', order: 5 },
          { name: '(2025) Fatrap Welcome to the basics', icon: 'gallery', path: '/gallery/2025-welcome-to-basics', order: 6 },
          { name: '(2025) Fatrap x Court', icon: 'gallery', path: '/gallery/2025-fatrap-court', order: 7 },
          { name: "(2025) Fatrap Pa' esa mierda ya no tengo tiempo", icon: 'gallery', path: '/gallery/2025-pa-esa-mierda', order: 8 },
        ],
      },
    },
  })

  // Create Contact us section
  const contact = await prisma.sidebarSection.create({
    data: {
      name: 'Contact us',
      order: 3,
      options: {
        create: [
          { name: 'Contact us', icon: 'mail', path: '/contact', order: 1 },
        ],
      },
    },
  })

  // Load Cloudinary URLs from JSON file generated by upload script
  const urlsPath = path.join(__dirname, '..', 'scripts', 'cloudinary-urls.json')
  if (fs.existsSync(urlsPath)) {
    const cloudinaryFiles: CloudinaryFile[] = JSON.parse(fs.readFileSync(urlsPath, 'utf-8'))
    console.log(`Loading ${cloudinaryFiles.length} files from cloudinary-urls.json...`)

    for (const file of cloudinaryFiles) {
      await prisma.fileItem.create({
        data: {
          name: file.name,
          type: file.type,
          thumbnail: file.thumbnail,
          path: file.path,
        },
      })
    }
    console.log(`${cloudinaryFiles.length} gallery files seeded.`)
  } else {
    console.log('No cloudinary-urls.json found. Skipping file seeding.')
  }

  console.log('Seed data created successfully!')
  console.log({ printFiles, gallery, contact })
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
